// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chat_2eproto;
namespace mmo {
class ChatMessage;
struct ChatMessageDefaultTypeInternal;
extern ChatMessageDefaultTypeInternal _ChatMessage_default_instance_;
class GetChatHistoryRequest;
struct GetChatHistoryRequestDefaultTypeInternal;
extern GetChatHistoryRequestDefaultTypeInternal _GetChatHistoryRequest_default_instance_;
class GetChatHistoryResponse;
struct GetChatHistoryResponseDefaultTypeInternal;
extern GetChatHistoryResponseDefaultTypeInternal _GetChatHistoryResponse_default_instance_;
class ReceiveChatNotify;
struct ReceiveChatNotifyDefaultTypeInternal;
extern ReceiveChatNotifyDefaultTypeInternal _ReceiveChatNotify_default_instance_;
class SendChatRequest;
struct SendChatRequestDefaultTypeInternal;
extern SendChatRequestDefaultTypeInternal _SendChatRequest_default_instance_;
class SendChatResponse;
struct SendChatResponseDefaultTypeInternal;
extern SendChatResponseDefaultTypeInternal _SendChatResponse_default_instance_;
}  // namespace mmo
PROTOBUF_NAMESPACE_OPEN
template<> ::mmo::ChatMessage* Arena::CreateMaybeMessage<::mmo::ChatMessage>(Arena*);
template<> ::mmo::GetChatHistoryRequest* Arena::CreateMaybeMessage<::mmo::GetChatHistoryRequest>(Arena*);
template<> ::mmo::GetChatHistoryResponse* Arena::CreateMaybeMessage<::mmo::GetChatHistoryResponse>(Arena*);
template<> ::mmo::ReceiveChatNotify* Arena::CreateMaybeMessage<::mmo::ReceiveChatNotify>(Arena*);
template<> ::mmo::SendChatRequest* Arena::CreateMaybeMessage<::mmo::SendChatRequest>(Arena*);
template<> ::mmo::SendChatResponse* Arena::CreateMaybeMessage<::mmo::SendChatResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mmo {

enum ChatChannel : int {
  CHANNEL_WORLD = 0,
  CHANNEL_PRIVATE = 1,
  CHANNEL_GUILD = 2,
  CHANNEL_TEAM = 3,
  CHANNEL_SYSTEM = 4,
  ChatChannel_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ChatChannel_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ChatChannel_IsValid(int value);
constexpr ChatChannel ChatChannel_MIN = CHANNEL_WORLD;
constexpr ChatChannel ChatChannel_MAX = CHANNEL_SYSTEM;
constexpr int ChatChannel_ARRAYSIZE = ChatChannel_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ChatChannel_descriptor();
template<typename T>
inline const std::string& ChatChannel_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ChatChannel>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ChatChannel_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ChatChannel_descriptor(), enum_t_value);
}
inline bool ChatChannel_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ChatChannel* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ChatChannel>(
    ChatChannel_descriptor(), name, value);
}
// ===================================================================

class ChatMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mmo.ChatMessage) */ {
 public:
  inline ChatMessage() : ChatMessage(nullptr) {}
  ~ChatMessage() override;
  explicit PROTOBUF_CONSTEXPR ChatMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatMessage(const ChatMessage& from);
  ChatMessage(ChatMessage&& from) noexcept
    : ChatMessage() {
    *this = ::std::move(from);
  }

  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatMessage& operator=(ChatMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatMessage* internal_default_instance() {
    return reinterpret_cast<const ChatMessage*>(
               &_ChatMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChatMessage& a, ChatMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatMessage& from) {
    ChatMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mmo.ChatMessage";
  }
  protected:
  explicit ChatMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSenderNameFieldNumber = 2,
    kContentFieldNumber = 4,
    kSenderIdFieldNumber = 1,
    kTimestampFieldNumber = 5,
    kTargetIdFieldNumber = 6,
    kChannelFieldNumber = 3,
  };
  // string sender_name = 2;
  void clear_sender_name();
  const std::string& sender_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_name();
  PROTOBUF_NODISCARD std::string* release_sender_name();
  void set_allocated_sender_name(std::string* sender_name);
  private:
  const std::string& _internal_sender_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_name(const std::string& value);
  std::string* _internal_mutable_sender_name();
  public:

  // string content = 4;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // uint64 sender_id = 1;
  void clear_sender_id();
  uint64_t sender_id() const;
  void set_sender_id(uint64_t value);
  private:
  uint64_t _internal_sender_id() const;
  void _internal_set_sender_id(uint64_t value);
  public:

  // int64 timestamp = 5;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // uint64 target_id = 6;
  void clear_target_id();
  uint64_t target_id() const;
  void set_target_id(uint64_t value);
  private:
  uint64_t _internal_target_id() const;
  void _internal_set_target_id(uint64_t value);
  public:

  // .mmo.ChatChannel channel = 3;
  void clear_channel();
  ::mmo::ChatChannel channel() const;
  void set_channel(::mmo::ChatChannel value);
  private:
  ::mmo::ChatChannel _internal_channel() const;
  void _internal_set_channel(::mmo::ChatChannel value);
  public:

  // @@protoc_insertion_point(class_scope:mmo.ChatMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    uint64_t sender_id_;
    int64_t timestamp_;
    uint64_t target_id_;
    int channel_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class SendChatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mmo.SendChatRequest) */ {
 public:
  inline SendChatRequest() : SendChatRequest(nullptr) {}
  ~SendChatRequest() override;
  explicit PROTOBUF_CONSTEXPR SendChatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendChatRequest(const SendChatRequest& from);
  SendChatRequest(SendChatRequest&& from) noexcept
    : SendChatRequest() {
    *this = ::std::move(from);
  }

  inline SendChatRequest& operator=(const SendChatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendChatRequest& operator=(SendChatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendChatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendChatRequest* internal_default_instance() {
    return reinterpret_cast<const SendChatRequest*>(
               &_SendChatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SendChatRequest& a, SendChatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SendChatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendChatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendChatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendChatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendChatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendChatRequest& from) {
    SendChatRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendChatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mmo.SendChatRequest";
  }
  protected:
  explicit SendChatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 2,
    kTargetIdFieldNumber = 3,
    kChannelFieldNumber = 1,
  };
  // string content = 2;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // uint64 target_id = 3;
  void clear_target_id();
  uint64_t target_id() const;
  void set_target_id(uint64_t value);
  private:
  uint64_t _internal_target_id() const;
  void _internal_set_target_id(uint64_t value);
  public:

  // .mmo.ChatChannel channel = 1;
  void clear_channel();
  ::mmo::ChatChannel channel() const;
  void set_channel(::mmo::ChatChannel value);
  private:
  ::mmo::ChatChannel _internal_channel() const;
  void _internal_set_channel(::mmo::ChatChannel value);
  public:

  // @@protoc_insertion_point(class_scope:mmo.SendChatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    uint64_t target_id_;
    int channel_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class SendChatResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mmo.SendChatResponse) */ {
 public:
  inline SendChatResponse() : SendChatResponse(nullptr) {}
  ~SendChatResponse() override;
  explicit PROTOBUF_CONSTEXPR SendChatResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendChatResponse(const SendChatResponse& from);
  SendChatResponse(SendChatResponse&& from) noexcept
    : SendChatResponse() {
    *this = ::std::move(from);
  }

  inline SendChatResponse& operator=(const SendChatResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendChatResponse& operator=(SendChatResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendChatResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendChatResponse* internal_default_instance() {
    return reinterpret_cast<const SendChatResponse*>(
               &_SendChatResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SendChatResponse& a, SendChatResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SendChatResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendChatResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendChatResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendChatResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendChatResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendChatResponse& from) {
    SendChatResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendChatResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mmo.SendChatResponse";
  }
  protected:
  explicit SendChatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // .mmo.Result result = 1;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const ::mmo::Result& result() const;
  PROTOBUF_NODISCARD ::mmo::Result* release_result();
  ::mmo::Result* mutable_result();
  void set_allocated_result(::mmo::Result* result);
  private:
  const ::mmo::Result& _internal_result() const;
  ::mmo::Result* _internal_mutable_result();
  public:
  void unsafe_arena_set_allocated_result(
      ::mmo::Result* result);
  ::mmo::Result* unsafe_arena_release_result();

  // @@protoc_insertion_point(class_scope:mmo.SendChatResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::mmo::Result* result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class ReceiveChatNotify final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mmo.ReceiveChatNotify) */ {
 public:
  inline ReceiveChatNotify() : ReceiveChatNotify(nullptr) {}
  ~ReceiveChatNotify() override;
  explicit PROTOBUF_CONSTEXPR ReceiveChatNotify(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReceiveChatNotify(const ReceiveChatNotify& from);
  ReceiveChatNotify(ReceiveChatNotify&& from) noexcept
    : ReceiveChatNotify() {
    *this = ::std::move(from);
  }

  inline ReceiveChatNotify& operator=(const ReceiveChatNotify& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReceiveChatNotify& operator=(ReceiveChatNotify&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReceiveChatNotify& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReceiveChatNotify* internal_default_instance() {
    return reinterpret_cast<const ReceiveChatNotify*>(
               &_ReceiveChatNotify_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ReceiveChatNotify& a, ReceiveChatNotify& b) {
    a.Swap(&b);
  }
  inline void Swap(ReceiveChatNotify* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReceiveChatNotify* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReceiveChatNotify* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReceiveChatNotify>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReceiveChatNotify& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReceiveChatNotify& from) {
    ReceiveChatNotify::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReceiveChatNotify* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mmo.ReceiveChatNotify";
  }
  protected:
  explicit ReceiveChatNotify(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // .mmo.ChatMessage message = 1;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const ::mmo::ChatMessage& message() const;
  PROTOBUF_NODISCARD ::mmo::ChatMessage* release_message();
  ::mmo::ChatMessage* mutable_message();
  void set_allocated_message(::mmo::ChatMessage* message);
  private:
  const ::mmo::ChatMessage& _internal_message() const;
  ::mmo::ChatMessage* _internal_mutable_message();
  public:
  void unsafe_arena_set_allocated_message(
      ::mmo::ChatMessage* message);
  ::mmo::ChatMessage* unsafe_arena_release_message();

  // @@protoc_insertion_point(class_scope:mmo.ReceiveChatNotify)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::mmo::ChatMessage* message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class GetChatHistoryRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mmo.GetChatHistoryRequest) */ {
 public:
  inline GetChatHistoryRequest() : GetChatHistoryRequest(nullptr) {}
  ~GetChatHistoryRequest() override;
  explicit PROTOBUF_CONSTEXPR GetChatHistoryRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetChatHistoryRequest(const GetChatHistoryRequest& from);
  GetChatHistoryRequest(GetChatHistoryRequest&& from) noexcept
    : GetChatHistoryRequest() {
    *this = ::std::move(from);
  }

  inline GetChatHistoryRequest& operator=(const GetChatHistoryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetChatHistoryRequest& operator=(GetChatHistoryRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetChatHistoryRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetChatHistoryRequest* internal_default_instance() {
    return reinterpret_cast<const GetChatHistoryRequest*>(
               &_GetChatHistoryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(GetChatHistoryRequest& a, GetChatHistoryRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetChatHistoryRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetChatHistoryRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetChatHistoryRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetChatHistoryRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetChatHistoryRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetChatHistoryRequest& from) {
    GetChatHistoryRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetChatHistoryRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mmo.GetChatHistoryRequest";
  }
  protected:
  explicit GetChatHistoryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChannelFieldNumber = 1,
    kCountFieldNumber = 2,
  };
  // .mmo.ChatChannel channel = 1;
  void clear_channel();
  ::mmo::ChatChannel channel() const;
  void set_channel(::mmo::ChatChannel value);
  private:
  ::mmo::ChatChannel _internal_channel() const;
  void _internal_set_channel(::mmo::ChatChannel value);
  public:

  // int32 count = 2;
  void clear_count();
  int32_t count() const;
  void set_count(int32_t value);
  private:
  int32_t _internal_count() const;
  void _internal_set_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:mmo.GetChatHistoryRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int channel_;
    int32_t count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class GetChatHistoryResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mmo.GetChatHistoryResponse) */ {
 public:
  inline GetChatHistoryResponse() : GetChatHistoryResponse(nullptr) {}
  ~GetChatHistoryResponse() override;
  explicit PROTOBUF_CONSTEXPR GetChatHistoryResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetChatHistoryResponse(const GetChatHistoryResponse& from);
  GetChatHistoryResponse(GetChatHistoryResponse&& from) noexcept
    : GetChatHistoryResponse() {
    *this = ::std::move(from);
  }

  inline GetChatHistoryResponse& operator=(const GetChatHistoryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetChatHistoryResponse& operator=(GetChatHistoryResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetChatHistoryResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetChatHistoryResponse* internal_default_instance() {
    return reinterpret_cast<const GetChatHistoryResponse*>(
               &_GetChatHistoryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GetChatHistoryResponse& a, GetChatHistoryResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetChatHistoryResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetChatHistoryResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetChatHistoryResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetChatHistoryResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetChatHistoryResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetChatHistoryResponse& from) {
    GetChatHistoryResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetChatHistoryResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mmo.GetChatHistoryResponse";
  }
  protected:
  explicit GetChatHistoryResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessagesFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // repeated .mmo.ChatMessage messages = 2;
  int messages_size() const;
  private:
  int _internal_messages_size() const;
  public:
  void clear_messages();
  ::mmo::ChatMessage* mutable_messages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mmo::ChatMessage >*
      mutable_messages();
  private:
  const ::mmo::ChatMessage& _internal_messages(int index) const;
  ::mmo::ChatMessage* _internal_add_messages();
  public:
  const ::mmo::ChatMessage& messages(int index) const;
  ::mmo::ChatMessage* add_messages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mmo::ChatMessage >&
      messages() const;

  // .mmo.Result result = 1;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const ::mmo::Result& result() const;
  PROTOBUF_NODISCARD ::mmo::Result* release_result();
  ::mmo::Result* mutable_result();
  void set_allocated_result(::mmo::Result* result);
  private:
  const ::mmo::Result& _internal_result() const;
  ::mmo::Result* _internal_mutable_result();
  public:
  void unsafe_arena_set_allocated_result(
      ::mmo::Result* result);
  ::mmo::Result* unsafe_arena_release_result();

  // @@protoc_insertion_point(class_scope:mmo.GetChatHistoryResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mmo::ChatMessage > messages_;
    ::mmo::Result* result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChatMessage

// uint64 sender_id = 1;
inline void ChatMessage::clear_sender_id() {
  _impl_.sender_id_ = uint64_t{0u};
}
inline uint64_t ChatMessage::_internal_sender_id() const {
  return _impl_.sender_id_;
}
inline uint64_t ChatMessage::sender_id() const {
  // @@protoc_insertion_point(field_get:mmo.ChatMessage.sender_id)
  return _internal_sender_id();
}
inline void ChatMessage::_internal_set_sender_id(uint64_t value) {
  
  _impl_.sender_id_ = value;
}
inline void ChatMessage::set_sender_id(uint64_t value) {
  _internal_set_sender_id(value);
  // @@protoc_insertion_point(field_set:mmo.ChatMessage.sender_id)
}

// string sender_name = 2;
inline void ChatMessage::clear_sender_name() {
  _impl_.sender_name_.ClearToEmpty();
}
inline const std::string& ChatMessage::sender_name() const {
  // @@protoc_insertion_point(field_get:mmo.ChatMessage.sender_name)
  return _internal_sender_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_sender_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mmo.ChatMessage.sender_name)
}
inline std::string* ChatMessage::mutable_sender_name() {
  std::string* _s = _internal_mutable_sender_name();
  // @@protoc_insertion_point(field_mutable:mmo.ChatMessage.sender_name)
  return _s;
}
inline const std::string& ChatMessage::_internal_sender_name() const {
  return _impl_.sender_name_.Get();
}
inline void ChatMessage::_internal_set_sender_name(const std::string& value) {
  
  _impl_.sender_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_sender_name() {
  
  return _impl_.sender_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_sender_name() {
  // @@protoc_insertion_point(field_release:mmo.ChatMessage.sender_name)
  return _impl_.sender_name_.Release();
}
inline void ChatMessage::set_allocated_sender_name(std::string* sender_name) {
  if (sender_name != nullptr) {
    
  } else {
    
  }
  _impl_.sender_name_.SetAllocated(sender_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_name_.IsDefault()) {
    _impl_.sender_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mmo.ChatMessage.sender_name)
}

// .mmo.ChatChannel channel = 3;
inline void ChatMessage::clear_channel() {
  _impl_.channel_ = 0;
}
inline ::mmo::ChatChannel ChatMessage::_internal_channel() const {
  return static_cast< ::mmo::ChatChannel >(_impl_.channel_);
}
inline ::mmo::ChatChannel ChatMessage::channel() const {
  // @@protoc_insertion_point(field_get:mmo.ChatMessage.channel)
  return _internal_channel();
}
inline void ChatMessage::_internal_set_channel(::mmo::ChatChannel value) {
  
  _impl_.channel_ = value;
}
inline void ChatMessage::set_channel(::mmo::ChatChannel value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:mmo.ChatMessage.channel)
}

// string content = 4;
inline void ChatMessage::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& ChatMessage::content() const {
  // @@protoc_insertion_point(field_get:mmo.ChatMessage.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mmo.ChatMessage.content)
}
inline std::string* ChatMessage::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:mmo.ChatMessage.content)
  return _s;
}
inline const std::string& ChatMessage::_internal_content() const {
  return _impl_.content_.Get();
}
inline void ChatMessage::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_content() {
  // @@protoc_insertion_point(field_release:mmo.ChatMessage.content)
  return _impl_.content_.Release();
}
inline void ChatMessage::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mmo.ChatMessage.content)
}

// int64 timestamp = 5;
inline void ChatMessage::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t ChatMessage::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t ChatMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:mmo.ChatMessage.timestamp)
  return _internal_timestamp();
}
inline void ChatMessage::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void ChatMessage::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:mmo.ChatMessage.timestamp)
}

// uint64 target_id = 6;
inline void ChatMessage::clear_target_id() {
  _impl_.target_id_ = uint64_t{0u};
}
inline uint64_t ChatMessage::_internal_target_id() const {
  return _impl_.target_id_;
}
inline uint64_t ChatMessage::target_id() const {
  // @@protoc_insertion_point(field_get:mmo.ChatMessage.target_id)
  return _internal_target_id();
}
inline void ChatMessage::_internal_set_target_id(uint64_t value) {
  
  _impl_.target_id_ = value;
}
inline void ChatMessage::set_target_id(uint64_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:mmo.ChatMessage.target_id)
}

// -------------------------------------------------------------------

// SendChatRequest

// .mmo.ChatChannel channel = 1;
inline void SendChatRequest::clear_channel() {
  _impl_.channel_ = 0;
}
inline ::mmo::ChatChannel SendChatRequest::_internal_channel() const {
  return static_cast< ::mmo::ChatChannel >(_impl_.channel_);
}
inline ::mmo::ChatChannel SendChatRequest::channel() const {
  // @@protoc_insertion_point(field_get:mmo.SendChatRequest.channel)
  return _internal_channel();
}
inline void SendChatRequest::_internal_set_channel(::mmo::ChatChannel value) {
  
  _impl_.channel_ = value;
}
inline void SendChatRequest::set_channel(::mmo::ChatChannel value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:mmo.SendChatRequest.channel)
}

// string content = 2;
inline void SendChatRequest::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& SendChatRequest::content() const {
  // @@protoc_insertion_point(field_get:mmo.SendChatRequest.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SendChatRequest::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mmo.SendChatRequest.content)
}
inline std::string* SendChatRequest::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:mmo.SendChatRequest.content)
  return _s;
}
inline const std::string& SendChatRequest::_internal_content() const {
  return _impl_.content_.Get();
}
inline void SendChatRequest::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* SendChatRequest::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* SendChatRequest::release_content() {
  // @@protoc_insertion_point(field_release:mmo.SendChatRequest.content)
  return _impl_.content_.Release();
}
inline void SendChatRequest::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mmo.SendChatRequest.content)
}

// uint64 target_id = 3;
inline void SendChatRequest::clear_target_id() {
  _impl_.target_id_ = uint64_t{0u};
}
inline uint64_t SendChatRequest::_internal_target_id() const {
  return _impl_.target_id_;
}
inline uint64_t SendChatRequest::target_id() const {
  // @@protoc_insertion_point(field_get:mmo.SendChatRequest.target_id)
  return _internal_target_id();
}
inline void SendChatRequest::_internal_set_target_id(uint64_t value) {
  
  _impl_.target_id_ = value;
}
inline void SendChatRequest::set_target_id(uint64_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:mmo.SendChatRequest.target_id)
}

// -------------------------------------------------------------------

// SendChatResponse

// .mmo.Result result = 1;
inline bool SendChatResponse::_internal_has_result() const {
  return this != internal_default_instance() && _impl_.result_ != nullptr;
}
inline bool SendChatResponse::has_result() const {
  return _internal_has_result();
}
inline const ::mmo::Result& SendChatResponse::_internal_result() const {
  const ::mmo::Result* p = _impl_.result_;
  return p != nullptr ? *p : reinterpret_cast<const ::mmo::Result&>(
      ::mmo::_Result_default_instance_);
}
inline const ::mmo::Result& SendChatResponse::result() const {
  // @@protoc_insertion_point(field_get:mmo.SendChatResponse.result)
  return _internal_result();
}
inline void SendChatResponse::unsafe_arena_set_allocated_result(
    ::mmo::Result* result) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.result_);
  }
  _impl_.result_ = result;
  if (result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mmo.SendChatResponse.result)
}
inline ::mmo::Result* SendChatResponse::release_result() {
  
  ::mmo::Result* temp = _impl_.result_;
  _impl_.result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mmo::Result* SendChatResponse::unsafe_arena_release_result() {
  // @@protoc_insertion_point(field_release:mmo.SendChatResponse.result)
  
  ::mmo::Result* temp = _impl_.result_;
  _impl_.result_ = nullptr;
  return temp;
}
inline ::mmo::Result* SendChatResponse::_internal_mutable_result() {
  
  if (_impl_.result_ == nullptr) {
    auto* p = CreateMaybeMessage<::mmo::Result>(GetArenaForAllocation());
    _impl_.result_ = p;
  }
  return _impl_.result_;
}
inline ::mmo::Result* SendChatResponse::mutable_result() {
  ::mmo::Result* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:mmo.SendChatResponse.result)
  return _msg;
}
inline void SendChatResponse::set_allocated_result(::mmo::Result* result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.result_);
  }
  if (result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(result));
    if (message_arena != submessage_arena) {
      result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.result_ = result;
  // @@protoc_insertion_point(field_set_allocated:mmo.SendChatResponse.result)
}

// -------------------------------------------------------------------

// ReceiveChatNotify

// .mmo.ChatMessage message = 1;
inline bool ReceiveChatNotify::_internal_has_message() const {
  return this != internal_default_instance() && _impl_.message_ != nullptr;
}
inline bool ReceiveChatNotify::has_message() const {
  return _internal_has_message();
}
inline void ReceiveChatNotify::clear_message() {
  if (GetArenaForAllocation() == nullptr && _impl_.message_ != nullptr) {
    delete _impl_.message_;
  }
  _impl_.message_ = nullptr;
}
inline const ::mmo::ChatMessage& ReceiveChatNotify::_internal_message() const {
  const ::mmo::ChatMessage* p = _impl_.message_;
  return p != nullptr ? *p : reinterpret_cast<const ::mmo::ChatMessage&>(
      ::mmo::_ChatMessage_default_instance_);
}
inline const ::mmo::ChatMessage& ReceiveChatNotify::message() const {
  // @@protoc_insertion_point(field_get:mmo.ReceiveChatNotify.message)
  return _internal_message();
}
inline void ReceiveChatNotify::unsafe_arena_set_allocated_message(
    ::mmo::ChatMessage* message) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.message_);
  }
  _impl_.message_ = message;
  if (message) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mmo.ReceiveChatNotify.message)
}
inline ::mmo::ChatMessage* ReceiveChatNotify::release_message() {
  
  ::mmo::ChatMessage* temp = _impl_.message_;
  _impl_.message_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mmo::ChatMessage* ReceiveChatNotify::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_release:mmo.ReceiveChatNotify.message)
  
  ::mmo::ChatMessage* temp = _impl_.message_;
  _impl_.message_ = nullptr;
  return temp;
}
inline ::mmo::ChatMessage* ReceiveChatNotify::_internal_mutable_message() {
  
  if (_impl_.message_ == nullptr) {
    auto* p = CreateMaybeMessage<::mmo::ChatMessage>(GetArenaForAllocation());
    _impl_.message_ = p;
  }
  return _impl_.message_;
}
inline ::mmo::ChatMessage* ReceiveChatNotify::mutable_message() {
  ::mmo::ChatMessage* _msg = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:mmo.ReceiveChatNotify.message)
  return _msg;
}
inline void ReceiveChatNotify::set_allocated_message(::mmo::ChatMessage* message) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.message_;
  }
  if (message) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(message);
    if (message_arena != submessage_arena) {
      message = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, message, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.message_ = message;
  // @@protoc_insertion_point(field_set_allocated:mmo.ReceiveChatNotify.message)
}

// -------------------------------------------------------------------

// GetChatHistoryRequest

// .mmo.ChatChannel channel = 1;
inline void GetChatHistoryRequest::clear_channel() {
  _impl_.channel_ = 0;
}
inline ::mmo::ChatChannel GetChatHistoryRequest::_internal_channel() const {
  return static_cast< ::mmo::ChatChannel >(_impl_.channel_);
}
inline ::mmo::ChatChannel GetChatHistoryRequest::channel() const {
  // @@protoc_insertion_point(field_get:mmo.GetChatHistoryRequest.channel)
  return _internal_channel();
}
inline void GetChatHistoryRequest::_internal_set_channel(::mmo::ChatChannel value) {
  
  _impl_.channel_ = value;
}
inline void GetChatHistoryRequest::set_channel(::mmo::ChatChannel value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:mmo.GetChatHistoryRequest.channel)
}

// int32 count = 2;
inline void GetChatHistoryRequest::clear_count() {
  _impl_.count_ = 0;
}
inline int32_t GetChatHistoryRequest::_internal_count() const {
  return _impl_.count_;
}
inline int32_t GetChatHistoryRequest::count() const {
  // @@protoc_insertion_point(field_get:mmo.GetChatHistoryRequest.count)
  return _internal_count();
}
inline void GetChatHistoryRequest::_internal_set_count(int32_t value) {
  
  _impl_.count_ = value;
}
inline void GetChatHistoryRequest::set_count(int32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:mmo.GetChatHistoryRequest.count)
}

// -------------------------------------------------------------------

// GetChatHistoryResponse

// .mmo.Result result = 1;
inline bool GetChatHistoryResponse::_internal_has_result() const {
  return this != internal_default_instance() && _impl_.result_ != nullptr;
}
inline bool GetChatHistoryResponse::has_result() const {
  return _internal_has_result();
}
inline const ::mmo::Result& GetChatHistoryResponse::_internal_result() const {
  const ::mmo::Result* p = _impl_.result_;
  return p != nullptr ? *p : reinterpret_cast<const ::mmo::Result&>(
      ::mmo::_Result_default_instance_);
}
inline const ::mmo::Result& GetChatHistoryResponse::result() const {
  // @@protoc_insertion_point(field_get:mmo.GetChatHistoryResponse.result)
  return _internal_result();
}
inline void GetChatHistoryResponse::unsafe_arena_set_allocated_result(
    ::mmo::Result* result) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.result_);
  }
  _impl_.result_ = result;
  if (result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mmo.GetChatHistoryResponse.result)
}
inline ::mmo::Result* GetChatHistoryResponse::release_result() {
  
  ::mmo::Result* temp = _impl_.result_;
  _impl_.result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mmo::Result* GetChatHistoryResponse::unsafe_arena_release_result() {
  // @@protoc_insertion_point(field_release:mmo.GetChatHistoryResponse.result)
  
  ::mmo::Result* temp = _impl_.result_;
  _impl_.result_ = nullptr;
  return temp;
}
inline ::mmo::Result* GetChatHistoryResponse::_internal_mutable_result() {
  
  if (_impl_.result_ == nullptr) {
    auto* p = CreateMaybeMessage<::mmo::Result>(GetArenaForAllocation());
    _impl_.result_ = p;
  }
  return _impl_.result_;
}
inline ::mmo::Result* GetChatHistoryResponse::mutable_result() {
  ::mmo::Result* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:mmo.GetChatHistoryResponse.result)
  return _msg;
}
inline void GetChatHistoryResponse::set_allocated_result(::mmo::Result* result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.result_);
  }
  if (result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(result));
    if (message_arena != submessage_arena) {
      result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.result_ = result;
  // @@protoc_insertion_point(field_set_allocated:mmo.GetChatHistoryResponse.result)
}

// repeated .mmo.ChatMessage messages = 2;
inline int GetChatHistoryResponse::_internal_messages_size() const {
  return _impl_.messages_.size();
}
inline int GetChatHistoryResponse::messages_size() const {
  return _internal_messages_size();
}
inline void GetChatHistoryResponse::clear_messages() {
  _impl_.messages_.Clear();
}
inline ::mmo::ChatMessage* GetChatHistoryResponse::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:mmo.GetChatHistoryResponse.messages)
  return _impl_.messages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mmo::ChatMessage >*
GetChatHistoryResponse::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:mmo.GetChatHistoryResponse.messages)
  return &_impl_.messages_;
}
inline const ::mmo::ChatMessage& GetChatHistoryResponse::_internal_messages(int index) const {
  return _impl_.messages_.Get(index);
}
inline const ::mmo::ChatMessage& GetChatHistoryResponse::messages(int index) const {
  // @@protoc_insertion_point(field_get:mmo.GetChatHistoryResponse.messages)
  return _internal_messages(index);
}
inline ::mmo::ChatMessage* GetChatHistoryResponse::_internal_add_messages() {
  return _impl_.messages_.Add();
}
inline ::mmo::ChatMessage* GetChatHistoryResponse::add_messages() {
  ::mmo::ChatMessage* _add = _internal_add_messages();
  // @@protoc_insertion_point(field_add:mmo.GetChatHistoryResponse.messages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mmo::ChatMessage >&
GetChatHistoryResponse::messages() const {
  // @@protoc_insertion_point(field_list:mmo.GetChatHistoryResponse.messages)
  return _impl_.messages_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mmo

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::mmo::ChatChannel> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mmo::ChatChannel>() {
  return ::mmo::ChatChannel_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
